### ISSUE TITLE
role persistence

### ISSUE THREAD

**Issue by melmsie** [Devoxin/Parallax#13]
instead of just mute persistence, you could add role persist with all roles that parallax has perms to add to users

**Comment by Devoxin** [comment]
Partially fulfilled in 9f97453f6e27e889b416b19fb0a11ce4979bdb49

Probably won't add a thing to restore *all* roles due to the permission/role existence checks required, also because this may pose an issue for servers that are unaware of complete role restoration upon a user rejoining
