### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Priultimus** [Devoxin/Parallax#17]
Your README and License don't seem to match up. Your license permits commercial use whereas the README discourages it. Maybe find a different license, or I'm really dumb.

**Comment by Devoxin** [comment]
Oh I kinda neglected the license tbf. Will update asap

**Comment by Devoxin** [comment]
Just double-checked readme and license. I believe both are okay, while hosting this code for commercial consumption is strongly discouraged, I can't really prevent it outright. Best I can do is deny any support whatsoever and report any clones that I see in servers that publicly promote bots (i.e. bot lists) as per their rules, and request the owner take down their bot or remove offending parts of the code. Additionally, specific components of this code **can** be used commercially providing meaningful modifications have been made.
